# This is a basic workflow to help you get started with Actions

name: sentieri

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    #- cron: '0 11 */2 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    scheduled:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm install
      - run: node update
      - name: Commit and push if changed
        run: |-
           git config user.name "Automated"
           git config user.email "actions@users.noreply.github.com"
           git add geojson gpx dati
           timestamp=$(date -u)
           git commit -m "Latest data: ${timestamp}"
           git push
